### ISSUE TITLE
Too many files seems to stress some js scripts

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-files#339]
Opening a directory with a large number a files seems to trigger a js script that takes ages to execute. My firefox opens a popup informing me that it takes too long and offers me the choice of killing it.
After few "let it run a bit", I decided to kill it. Finally, I can see the files (not sure they are all listed though), with the last line of the page being "This folder is empty." (I guess it's a side effect of killing the script... ?)

It's a bit problematic as this directory contains the sync of my phone's pictures... I'm not that convinced that this backup is in a healthy state ...

**Comment by jsilvestre** [comment]
Thank your for the report.
It is unfortunately a long lasting issue. We're working on a solution for that specific matter, in a way that we can reuse it in other applications. It should be a matter of days before the first piece of it are released.

I'm closing the ticket, not because it's irrelevant, but there is already one: https://github.com/cozy/cozy-files/issues/223

Thank you for your patience!
