### ISSUE TITLE
"Picture icon" not displayed for images imported prior  to  publication of version 1.1.14

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-files#361]
The images in files imported before publication of version 1.1.14 of files do not have the good icone. It is a blank icone instead of the picture icon

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro,

@aenario / @jsilvestre : do you think this is related to a MIME problem and we should add a command to fix it ?

Maybe should we add this command in npm postinstall ?

**Comment by aenario** [comment]
Yes, the mime type / class is determined upon upload, older files should be reindexed.

We cant add it at postinstall, because we dont have the necessary env to have permission to read files from the DS. We can however add a view to fetch all files without mime-type/class and reindex them and run this function on application startup.

**Comment by aenario** [comment]
Alternatively, we could use the mime/type provided by cozydb and make the class at view time
```
{
  "_id": "0077DD90-8149-C972-A259-D635CCB77428",
  "_rev": "2-27cefe17e69e08fd459808d9d24c4f81",
  "docType": "Binary",
  "_attachments": {
    "file": {
      "content_type": "image/jpeg",
      "revpos": 2,
      "digest": "md5-ekuz4cTSNmEtMZ+091FQPw==",
      "length": 409999,
      "stub": true
    }
  }
}
```
